name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'

      - name: Deploy to GitHub Pages
        run: |
          mkdir dist
          cp index.html dist/
          cp styles.css dist/
          cp script.js dist/
          cp config.js dist/


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
